# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]
    
  schedule:
  - cron: "0 0 * * 0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
      
    - name: install denpends
      run: |
        sudo apt-get update 
        sudo apt-get install -y wget curl grep gzip findutils git
    
    - name: run the script
      run: |
        git clone https://github.com/Naunter/BT_BlockLists.git
        cd BT_BlockLists
        chmod 740 ./update.sh
        ./update.sh
            
    - name: copy the file to repo
      run: |
        ls -al /
        ls -al BT_BlockLists
        cp /tmp/bt_blocklists.gz BT_BlockLists/bt_blocklists.gz
    
    - name: Commit files
      run: |
        git config --local user.email "naunter@github.com"
        git config --local user.name "naunter"
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
